### ISSUE TITLE
Dropping Messages to log insight

### ISSUE THREAD

**Issue by bradgoodman** [pivotalservices/firehose-to-loginsight#2] opened 2017-01-10 22:36 UTC
We are having issues in multiple foundations where all syslogs will drop for a short period of time and will eventually start working again. There are times when the app has to be restage/restarted inside of PCF. The scenario I've seen most often is when an application is sending a log message, but its not being sent off to log insight. We are able to track when a log message is dropped because we currently have an app sending a ping message every minute.

**Comment by calebwashburn** [comment] 2017-01-10 23:42
Are you able to see all these messages or loss of mesages in the firehose using `cf logs <appname>`  Trying to derive if there is data loss in delivery to the firehose or in sending to log insight?  There shouldn't be any need to restage an application for events to show up, so if able to re-produce this can you provide steps to do so.

**Comment by andr01droth** [comment] 2017-01-11 01:16
@calebwashburn to help keep track of missed messages, we deployed a very simple "tracer" app that does nothing but print  timestamp and count to stdout once a minute.  The count is just the current minute.   We setup loginsight to notify us if we see less than 5 messages in 5 minutes.   When we see the alerts we can go into loginsight and see a missed minute.   The app log itself has no misses.

I forked firehose-to-oinsight in an attempt to add a debug statement when messages from our "tracer" app were sent to loginsight - unfortunately inspecting every message caused the fork to continuousy get kicked from firehose as a slow consumer, so I abandoned it.

let us know if you have any ideas of where we can some diag to help understand where the messages are dropping.

**Comment by z4ce** [comment] 2017-01-11 02:53
It is worth noting that Brad also looked for dropped messages value metric,
but didn't find any which indicates that the nozzle is at least consuming
the event.

**Comment by andr01droth** [comment] 2017-01-25 21:03
I believe the nozzle is choking due to back pressure -- I think we are just pushing beyond the capacity of the LI ingestion api.   I would be okay with closing this issue.  We are investigating alternate solutions.

**Comment by tehkuhnz** [comment] 2017-02-08 18:56
I am also seeing this issue across multiple foundations. 
Not sure if its related to back-pressure from the log insight ingestion API though... as each LI node should be able to sustain 15K/s messages. ( not getting anywhere near that per foundation)
Is anyone using the embedded loginsight load balancer?

**Comment by andr01droth** [comment] 2017-02-09 05:50
@tehkuhnz we are not using the load balancer.   In  my testing I could push ~ 25k msg/sec of syslog.  I would see some slowness / lag  but not too lossy overall (that I could tell, though admittedly, I was only tracking certain messages).    

When using the ingestion API (with no syslog), I would start having problems with nozzle when the ingestion API was sustaining as few as 2400-2600 msg/sec.

**Comment by tehkuhnz** [comment] 2017-07-18 13:27
I can confirm that after deploying version`v0.0.16` we are not having any issues with the nozzle crashing or dropping messages. Also our LI environment has been handling 50K/sec messages over the ingestion API so we are not too concerned about back pressure from LI anymore.

**Comment by jprateekvmware** [comment] 2017-08-09 16:52
How many instance of loginsigh you have running with how much memory, we are facing a problem of dropped message too and i have it running on the latest .16 version

**Closed as completed** 2021-05-19 22:45 UTC
